# Generated by Django 4.2.5 on 2023-10-06 02:00

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_published', models.DateTimeField(verbose_name='date published')),
                ('article_content', tinymce.models.HTMLField()),
            ],
        ),
    ]
