# Generated by Django 4.2.5 on 2023-10-07 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articletwo',
        ),
    ]
